/*
 * Stub for class kobi.chess.NewChessManager
 * Generated by Sapphire Compiler (sc).
 */
package kobi.chess.stubs;


public final class NewChessManager_Stub extends kobi.chess.NewChessManager implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public NewChessManager_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of getSimpleEngine()
    public engine.SimpleEngine getSimpleEngine() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getSimpleEngine();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public engine.SimpleEngine kobi.chess.NewChessManager.getSimpleEngine()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((engine.SimpleEngine) $__result);
    }

    // Implementation of getSamplePrintManager()
    public kobi.chess.SamplePrint getSamplePrintManager() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                $__result = super.getSamplePrintManager();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public kobi.chess.SamplePrint kobi.chess.NewChessManager.getSamplePrintManager()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return ((kobi.chess.SamplePrint) $__result);
    }
}
