/*
 * Stub for class kobi.chess.SamplePrint
 * Generated by Sapphire Compiler (sc).
 */
package kobi.chess.stubs;


public final class SamplePrint_Stub extends kobi.chess.SamplePrint implements sapphire.common.AppObjectStub {

    sapphire.policy.SapphirePolicy.SapphireClientPolicy $__client = null;
    boolean $__directInvocation = false;

    public SamplePrint_Stub () {
        super();
    }


    public void $__initialize(sapphire.policy.SapphirePolicy.SapphireClientPolicy client) {
        $__client = client;
    }

    public void $__initialize(boolean directInvocation) {
        $__directInvocation = directInvocation;
    }

    public Object $__clone() throws CloneNotSupportedException {
        return super.clone();
    }



    // Implementation of printSampleLine3()
    public void printSampleLine3() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.printSampleLine3();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void kobi.chess.SamplePrint.printSampleLine3()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of printSampleLine2()
    public void printSampleLine2() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.printSampleLine2();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void kobi.chess.SamplePrint.printSampleLine2()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Implementation of printSampleLine()
    public void printSampleLine() {
        java.lang.Object $__result = null;
        try {
            if ($__directInvocation)
                super.printSampleLine();
            else {
                java.util.ArrayList<Object> $__params = new java.util.ArrayList<Object>();
                String $__method = "public void kobi.chess.SamplePrint.printSampleLine()";
                $__result = $__client.onRPC($__method, $__params);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}
